apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openshift-ai-maas-workshop
  title: OpenShift AI Models-as-a-Service Workshop
  description: A 20-minute Python lab connecting to a private Granite LLM on OpenShift AI.
  tags:
    - python
    - ai
    - workshop
  # links:
  #   - url: https://<openshift-cluster>/#<hosted-git-repo>
  #     title: 🚀 Open in Dev Spaces
  #     icon: web
spec:
  type: module
  lifecycle: production
  owner: group:default/workshop-admins
  subcomponentOf: component:default/workshop-repository